version: '2'

services:
  app1:
    image: mtejeda/survey4
    environment:
      MONGO_URL: "mongodb://db/unq"
    depends_on:
      - db
    ports:
      - "9090:9090"
  app2:
      image: mtejeda/survey4
      environment:
        MONGO_URL: "mongodb://db/unq"
      depends_on:
        - db
      ports:
        - "9090:9090"
  db:
    image: mtejeda/mongo_survey

  locust:
    build: locust
    ports:
      - "8089:8089"

  haproxy:
    image: tutum/haproxy:latest
    links:
     - app1
     - app2
    ports:
     - "9090:9090"
